config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    'help' => 'static_pages#help'
  get    'home' => 'static_pages#home'
  get    'about' => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup' => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'advanced_search' => 'advanced_searches#new'
  post 'advanced_search' => 'advanced_searches#create'
  get 'advanced_search/results' => 'advanced_searches#results'
  
  resources :posts, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :friends, only:%i[create destroy]
  resources :friend_requests, only: %i[create destroy]


  resources :users do
    member do
      get :likes
      get :buddies
      get :about
      get :received_requests
    end
  end


  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_like_form.html.erb
<% unless current_user?(post.user) %>
  <div id="like_form">
    <% if current_user.likes?(post) %>
      <%= render 'posts/unlike', post: post %>
    <% else %>
      <%= render 'posts/like', post: post %>
    <% end %>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<div class="create-post">

  <%= form_for(@post, html: { multipart: true }, remote: true) do |f| %>

    <div class="row">
      <%= render 'shared/error_messages' , object: f.object %>
    </div>
    <div class="row">
      <div class="col-md-7 col-sm-7">
        <div class="form-group">
          <%= f.text_area :caption,
                          placeholder: "Compose new post...",
                          cols:"30",
                          rows:"1",
                          class:"form-control" %>

        </div>
      </div>
      <div class="col-md-5 col-sm-5">
        <%= f.submit "Post", class: "btn btn-primary pull-right" %>
      </div>
    </div>
    <div class="row">
        <div class="checkbox ">
          <label><%= f.check_box :is_public,
                                 {class:"checkbox inline pull-left"},
                                 "true", "false"  %>
            Public
          </label>
        </div>
    </div>
    <div class="row">
      <div class="col-md-7 col-sm-7">
        <%= f.file_field :picture,
                         accept: 'image/jpeg,image/gif,image/png',
                         class: "form-control"%>
      </div>

    </div>

    <% end %>

</div>

app/views/shared/_starts.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= buddy_user_path(@user) %>">
    <strong id="buddy" class="stat">
      <%= @user.buddies.count %>
    </strong>
    Friends
  </a>

</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= buddies_user_path(@user) %>" class="active">

    <strong id="buddy" class="stat">
      <%= pluralize(@user.buddies.count,'Friend') %>
    </strong>

  </a>

</div>

app/views/shared/_user_info.html.erb
r<div class="profile-card">
  <img src="<%= current_user.avatar %>" alt="user" class="profile-photo" />

  <h5>
    <%= link_to current_user.full_name, user_path(current_user), class: "text-white"%>
  </h5>

  <a href="#" class="text-white">
    <i class="ion ion-android-person-add"></i>
    <%= pluralize(current_user.posts.count, "post") %>
  </a>
</div>