config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    'help' => 'static_pages#help'
  get    'home' => 'static_pages#home'
  get    'about' => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup' => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'advanced_search' => 'advanced_searches#new'
  post 'advanced_search' => 'advanced_searches#create'
  get 'advanced_search/results' => 'advanced_searches#results'
  
  resources :posts, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :friends, only:%i[create destroy]
  resources :friend_requests, only: %i[create destroy]


  resources :users do
    member do
      get :likes
      get :buddies
      get :about
      get :received_requests
    end
  end


  
end

app/models/advanced_search.rb
class AdvancedSearch
  extend ActiveModel::Naming
  include ActiveModel::Model
  attr_accessor :first_name, :last_name, :email, :city, :caption, :simple

  def results
    @results ||= find_results
  end

  def to_model
    # You will get to_model error, if you don't have this dummy method
  end

  # You need this otherwise you get an error
  def persisted?
    false
  end

  private

  def find_results
    user = User
    instance_variables.each(&:downcase)

    if simple.blank?
      user = user.joins(:posts) unless caption.blank?
      user = user.joins(:city) unless city.blank?
      user.where(conditions).distinct
    else
      user.where(conditions_simple).distinct
    end



  end

  def first_name_conditions
    ['first_name LIKE ?', "%#{first_name}%"] unless first_name.blank?
  end

  def last_name_conditions
    ['last_name LIKE ?', "%#{last_name}%"] unless last_name.blank?
  end

  def email_conditions
    ['email LIKE ?', "%#{email}%"] unless email.blank?
  end

  def caption_conditions
    ['caption LIKE ?', "%#{caption}%"] unless caption.blank?
  end

  def city_conditions
    ['cities.name LIKE ?', "%#{city}%"] unless city.blank?
  end

  def conditions
    [conditions_clauses.join(' AND '), *conditions_options]
  end

  def conditions_simple
    ['first_name like ? or last_name like ?',"%#{simple}%","%#{simple}%"]
  end

  def conditions_clauses
    conditions_parts.map(&:first)
  end

  def conditions_options
    conditions_parts.map { |condition| condition[1..-1] }.flatten
  end

  def conditions_parts
    private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
  end



end

app/controllers/advanced_searches_controller.rb
class AdvancedSearchesController < ApplicationController
  before_action :logged_in_user

  def results
    params[:advanced_search] = session[:advanced_search]

    @advanced_search = AdvancedSearch.new(advanced_search_params)

  end


  # GET /advanced_searches/new
  def new

  end


  # POST /advanced_searches
  def create
    session.delete(:advanced_search)
    session[:advanced_search] = advanced_search_params
    redirect_to advanced_search_results_path
  end


  private


  # Never trust parameters from the scary internet, only allow the white list through.
  def advanced_search_params
    params.require(:advanced_search).permit(:first_name,:simple,
                                            :last_name, :email,
                                            :city, :caption)
  end

  def logged_in_user
    unless helpers.logged_in?
      #helpers.store_location
      flash[:danger] = "please log in"
      redirect_to login_url
    end
  end

end

app/helpers/advanced_searches_helper.rb
module AdvancedSearchesHelper
end

app/views/advanced_searches/_form.html.erb
<%= form_with(model: advanced_search, local: true) do |form| %>
  <% if advanced_search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advanced_search.errors.count, "error") %> prohibited this advanced_search from being saved:</h2>

      <ul>
      <% advanced_search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :advanced_search_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :advanced_search_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :advanced_search_email %>
  </div>

  <div class="field">
    <%= form.label :hometown %>
    <%= form.text_field :hometown, id: :advanced_search_hometown %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption, id: :advanced_search_caption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advanced_searches/edit.html.erb
<h1>Editing Advanced Search</h1>

<%= render 'form', advanced_search: @advanced_search %>

<%= link_to 'Show', @advanced_search %> |
<%= link_to 'Back', advanced_searches_path %>

app/views/advanced_searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advanced Searches</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Hometown</th>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advanced_searches.each do |advanced_search| %>
      <tr>
        <td><%= advanced_search.first_name %></td>
        <td><%= advanced_search.last_name %></td>
        <td><%= advanced_search.email %></td>
        <td><%= advanced_search.hometown %></td>
        <td><%= advanced_search.caption %></td>
        <td><%= link_to 'Show', advanced_search %></td>
        <td><%= link_to 'Edit', edit_advanced_search_path(advanced_search) %></td>
        <td><%= link_to 'Destroy', advanced_search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advanced Search', new_advanced_search_path %>

app/views/advanced_searches/new.html.erb
<% provide(:title, "Advanced Search") %>
<h1>Advanced Search</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:advanced_search, url: advanced_search_path) do |f| %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :caption %>
      <%= f.text_field :caption, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/advanced_searches/results.html.erb
<div class="container">

  <hgroup class="mb20">
    <h1>Search Results</h1>
    <h2 class="lead">
      <strong class="text-danger"><%= pluralize(@advanced_search.results.count,'result') %></strong>
      found
    </h2>
  </hgroup>

  <section class="col-xs-12 col-sm-6 col-md-12">



    <% @advanced_search.results.each do |user| %>

      <article class="search-result row">
        <%= render user %>
      </article>

    <% end %>

  </section>
</div>

app/views/advanced_searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @advanced_search.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @advanced_search.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @advanced_search.email %>
</p>

<p>
  <strong>Hometown:</strong>
  <%= @advanced_search.hometown %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @advanced_search.caption %>
</p>

<%= link_to 'Edit', edit_advanced_search_path(@advanced_search) %> |
<%= link_to 'Back', advanced_searches_path %>