config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    'help' => 'static_pages#help'
  get    'home' => 'static_pages#home'
  get    'about' => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup' => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'advanced_search' => 'advanced_searches#new'
  post 'advanced_search' => 'advanced_searches#create'
  get 'advanced_search/results' => 'advanced_searches#results'
  
  resources :posts, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :friends, only:%i[create destroy]
  resources :friend_requests, only: %i[create destroy]


  resources :users do
    member do
      get :likes
      get :buddies
      get :about
      get :received_requests
    end
  end


  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  #default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :caption, presence: true , length: { maximum: 500 }
  validates :user_id, presence:true
  validate :picture_size
  private
# Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = helpers.current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "post created!"
      respond_to do |f|
          f.html{redirect_to root_url}
          f.js
      end
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

  private
  def post_params
    params.require(:post).permit(:caption,:picture,:is_public)
  end

  def logged_in_user
    unless helpers.logged_in?
      #helpers.store_location
      flash[:danger] = "please log in"
      redirect_to login_url
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, remote: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption, id: :post_caption %>
  </div>

  <div class="field">
    <%= form.label :is_public %>
    <%= form.check_box :is_public, id: :post_is_public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like.html.erb
<%= form_for(current_user.likes.build(post_id: post.id),remote: true ) do |f| %>
  <div><%= hidden_field_tag :post_id, post.id %></div>
  <%= f.submit "Like", class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post-content">

  <!-- post photo -->
  <img src="<%= post.picture.url unless post.picture.blank?%>"
       class="img-responsive post-image" >

  <div class="post-container" id="post-<%= post.id %>">

    <div class="post-detail">
      <div class="user-info">
          <%= link_to user_path(post.user)  do%>

          <h5>
            <%=post.user.full_name%>
          </h5>
          <%end%>
        <p class="text-muted"><%= time_ago_in_words(post.created_at) %> ago.</p>
      </div>

        <div class="likes reaction">

          <%= render 'shared/like_form', post: post %>
        </div>
      <div class="likes_count">
        <%= pluralize(post.likes.count,'person')%>  liked this post
      </div>
      <div class="line-divider"></div>
      <div class="post-text">
        <p>
          <%= post.caption %>
          <i class="em em-anguished"></i>
          <i class="em em-anguished"></i>
          <i class="em em-anguished"></i>
        </p>
      </div>
      <div class="line-divider"></div>


    </div>
  </div>
</div>

app/views/posts/_unlike.html.erb
<%= form_for(current_user.likes.find_by(post_id: post.id),
             html: { method: :delete }, remote: true) do |f| %>
  <div><%= hidden_field_tag :post_id, post.id %></div>
  <%= f.submit "Unlike", class: "btn-danger btn" %>
<% end %>

app/views/posts/create.js.erb
$('.posts').prepend("<%= escape_javascript(render @post) %>")
$('#post_caption').val('')

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Caption</th>
      <th>Is public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.caption %></td>
        <td><%= post.is_public %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= @post.caption %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @post.is_public %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>