config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    'help' => 'static_pages#help'
  get    'home' => 'static_pages#home'
  get    'about' => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup' => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'advanced_search' => 'advanced_searches#new'
  post 'advanced_search' => 'advanced_searches#create'
  get 'advanced_search/results' => 'advanced_searches#results'
  
  resources :posts, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :friends, only:%i[create destroy]
  resources :friend_requests, only: %i[create destroy]


  resources :users do
    member do
      get :likes
      get :buddies
      get :about
      get :received_requests
    end
  end


  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About"   %></li>
      <li><%= link_to "Contact" %></li>
      <li><%= link_to "News"    %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <%= render 'layouts/header_loggedin' %>
<% end %>

app/views/layouts/_header_loggedin.html.erb
<!-- Header ================================================= -->
<header id="header">
  <nav class="navbar navbar-default navbar-fixed-top menu">
    <div class="container">

      <div class="navbar-header">

        <button type="button"
                class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "logo.png", alt: "logo"%>
        <% end %>

      </div>



      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right main-menu">
          <li class="dropdown">
            <%= link_to "Advanced Search", advanced_search_path %>
          </li>
          <li class="dropdown">
            <%= link_to "News feed", home_path %>
          </li>
          <li class="dropdown">
            <%= link_to "Profile", user_path(current_user)  %>
          </li>
          <li class="dropdown">
            <%= link_to "Friend requests", received_requests_user_path(current_user) %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        </ul>
        <%= form_for :advanced_search,
                      url: advanced_search_path,
                      html:{class:"navbar-form navbar-right hidden-sm"} do |f| %>
          <div class="input-group">
            <%= f.text_field :simple,
                              class: 'form-control',
                              placeholder:"Search friends" %>
            <span class="input-group-btn">
              <%= f.submit "Search", class: "btn btn-primary" %>
            </span>
          </div>
        <% end %>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>
</header>
<!--Header End-->

app/views/layouts/_header_loggedout.html.erb
<!-- Header ================================================= -->
<header id="header">
  <nav class="navbar navbar-default navbar-fixed-top menu">
    <div class="container">

      <div class="navbar-header">

        <button type="button"
                class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to signup_path, class: "navbar-brand" do %>
          <%= image_tag "logo.png", alt: "logo"%>
        <% end %>

      </div>



      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right main-menu">
          <li class="dropdown">
            <%= link_to "News feed", home_path %>
          </li>
          <li class="dropdown">
            <%= link_to "Profile", user_path(current_user)  %>
          </li>
          <li class="dropdown">
            <%= link_to "Friend requests", user_path(current_user) %>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>

        </ul>

        <%= form_for current_user, html:{class:'navbar-form navbar-right hidden-sm'}  do |f| %>
          <div class="form-group">
            <%= f.text_field :first_name,
                             class:'form-control',
                             placeholder: "Search friends, photos, videos"%>
          </div>
        <% end %>




      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>
</header>
<!--Header End-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Keep Up</title>

  <!--Google Font-->
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700,700i" rel="stylesheet">

  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>